import {StyleSheet} from 'react-native';
import {white, lightBlue, darkBlue, darkgray,red,green} from './colors'

export const styles = StyleSheet.create ({
container: {
    flex: 1,
    backgroundColor: white,
    padding: 10,
},
item: {
    padding: 20,
    borderRadius: 10,
    marginLeft: 10,
    marginRight: 10,
    justifyContent: 'center',
    backgroundColor: lightBlue,
},
deckDetails: {
    flex: 1,
    padding: 5,
    backgroundColor: white,
    justifyContent: 'center',
},
deckTitle: {
    fontSize: 30,
    alignSelf: 'center',
    fontWeight: 'bold',
    justifyContent: 'center',
    marginLeft: 15,
},
addButton: {
    padding: 10,
    paddingLeft: 30,
    paddingRight: 30,
    justifyContent: 'center',
    borderWidth: 1,
    borderRadius: 5,
    height: 45,
    backgroundColor: darkBlue,
    alignItems: 'center',
    marginBottom: 30,
    marginLeft: 15,
    marginRight: 15,
    color: white,
},
textInput: {
    borderColor: 'darkgray',
    marginLeft: 10,
    marginRight: 20,
    borderWidth: 2,
    paddingLeft: 10,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
},
addContainer: {
    flex: 1,
    backgroundColor: white,
    justifyContent: 'space-around',
},
cardsNumber: {
    fontSize: 20,
    paddingTop: 20,
    paddingBottom: 20,
    color: darkgray,
    alignSelf: 'center',
},
submitButton: {
    padding: 10,
    paddingLeft: 30,
    paddingRight: 30,
    justifyContent: 'center',
    borderWidth: 1,
    borderRadius: 2,
    height: 45,
    backgroundColor: darkBlue,
    alignItems: 'center',
    marginBottom: 30,
    marginLeft: 15,
    marginRight: 15,
},
submitBtnText: {
    fontSize: 22,
    textAlign: 'center',
    color: white,
},

addCardButton: {
    padding: 10,
    paddingLeft: 30,
    paddingRight: 30,
    justifyContent: 'center',
    borderWidth: 1,
    borderRadius: 2,
    height: 45,
    backgroundColor: darkBlue,
    alignItems: 'center',
    marginBottom: 30,
},
startQuizButton: {
    padding: 10,
    paddingLeft: 30,
    paddingRight: 30,
    justifyContent: 'center',
    borderWidth: 1,
    borderRadius: 2,
    height: 45,
    backgroundColor: darkBlue,
    alignItems: 'center',
    marginBottom: 30,
},

redButton: {
    padding: 10,
    paddingLeft: 30,
    paddingRight: 30,
    justifyContent: 'center',
    borderWidth: 1,
    borderRadius: 2,
    height: 45,
    backgroundColor: red,
    alignItems: 'center',
    marginBottom: 30,
},
correctButton: {
    padding: 10,
    paddingLeft: 30,
    paddingRight: 30,
    justifyContent: 'center',
    borderWidth: 1,
    borderRadius: 2,
    height: 45,
    backgroundColor: green,
    alignItems: 'center',
    marginBottom: 30,
},
questionCard: {
    flex: 1,
    backgroundColor: white,
    padding: 5,
    justifyContent: 'center',
},
noQuestions: {
    flex: 1,
    backgroundColor: white,
    padding: 15,
    justifyContent: 'center',
},
restartQuizButton: {
    padding: 10,
    paddingLeft: 30,
    paddingRight: 30,
    justifyContent: 'center',
    borderWidth: 1,
    borderRadius: 2,
    height: 45,
    backgroundColor: darkBlue,
    alignItems: 'center',
    marginBottom: 30,
    marginTop: 100,
},
backToDeckButton: {
    padding: 10,
    paddingLeft: 30,
    paddingRight: 30,
    justifyContent: 'center',
    borderWidth: 1,
    borderRadius: 2,
    height: 45,
    backgroundColor:  darkgray,
    alignItems: 'center',
    marginBottom: 30,
},

});